-- Migration: catalog repricing pipeline (Sprint 6.5)
-- Date: 2026-08-12

create table if not exists public.catalog_repricing_jobs (
  id uuid primary key default gen_random_uuid(),
  trigger_source text not null default 'admin_panel',
  requested_by text,
  status text not null default 'PENDING'
    check (status in ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')),
  previous_settings jsonb,
  applied_settings jsonb not null,
  total_products integer not null default 0,
  processed_products integer not null default 0,
  succeeded_products integer not null default 0,
  failed_products integer not null default 0,
  error_summary text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_catalog_repricing_jobs_created_at
  on public.catalog_repricing_jobs(created_at desc);

create table if not exists public.catalog_price_snapshots (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.catalog_repricing_jobs(id) on delete cascade,
  product_id bigint not null,
  old_price_xof bigint not null,
  new_price_xof bigint not null,
  shipping_mode text,
  shipping_cost_xof bigint,
  base_cost_xof bigint,
  margin_percentage numeric,
  details jsonb,
  created_at timestamptz not null default now(),
  unique(job_id, product_id)
);

create index if not exists idx_catalog_price_snapshots_job_id
  on public.catalog_price_snapshots(job_id);

comment on table public.catalog_repricing_jobs is 'Batch jobs for global product catalog repricing';
comment on table public.catalog_price_snapshots is 'Per-product before/after snapshot generated by repricing jobs';

alter table public.catalog_repricing_jobs enable row level security;
alter table public.catalog_price_snapshots enable row level security;

drop policy if exists catalog_repricing_jobs_read_authenticated on public.catalog_repricing_jobs;
create policy catalog_repricing_jobs_read_authenticated
on public.catalog_repricing_jobs
for select
to authenticated
using (true);

drop policy if exists catalog_repricing_jobs_write_service_role on public.catalog_repricing_jobs;
create policy catalog_repricing_jobs_write_service_role
on public.catalog_repricing_jobs
for all
to authenticated
using (auth.jwt() ->> 'role' = 'service_role')
with check (auth.jwt() ->> 'role' = 'service_role');

drop policy if exists catalog_price_snapshots_read_authenticated on public.catalog_price_snapshots;
create policy catalog_price_snapshots_read_authenticated
on public.catalog_price_snapshots
for select
to authenticated
using (true);

drop policy if exists catalog_price_snapshots_write_service_role on public.catalog_price_snapshots;
create policy catalog_price_snapshots_write_service_role
on public.catalog_price_snapshots
for all
to authenticated
using (auth.jwt() ->> 'role' = 'service_role')
with check (auth.jwt() ->> 'role' = 'service_role');

grant select on public.catalog_repricing_jobs to authenticated;
grant select on public.catalog_price_snapshots to authenticated;

do $$
declare
  seq_name text;
begin
  seq_name := pg_get_serial_sequence('public.catalog_price_snapshots', 'id');
  if seq_name is not null then
    execute format('grant usage, select on sequence %s to authenticated', seq_name);
  end if;
end $$;
