-- Migration: create orders table for Doukoure Import
-- Date: 2026-08-12

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_ref text not null unique,
  customer_name text not null,
  customer_phone text not null,
  delivery_address text,
  product_name text not null,
  product_id text,
  shipping_option text not null,
  base_price_xof bigint not null default 0,
  deposit_paid_xof bigint not null default 0,
  balance_xof bigint not null default 0,
  estimated_weight numeric,
  actual_weight numeric,
  inspection_photo_url text,
  inspection_video_url text,
  status text not null default 'PAYMENT_PENDING',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_orders_order_ref on public.orders (order_ref);
create index if not exists idx_orders_created_at on public.orders (created_at desc);
create index if not exists idx_orders_status on public.orders (status);

comment on table public.orders is 'Customer orders created from the Doukoure Import storefront';
comment on column public.orders.order_ref is 'Human-readable order reference';
comment on column public.orders.deposit_paid_xof is 'Deposit collected at order confirmation';
comment on column public.orders.balance_xof is 'Remaining balance due at delivery';
comment on column public.orders.actual_weight is 'Measured weight after inspection';
comment on column public.orders.inspection_photo_url is 'Inspection photo URL from China warehouse';
comment on column public.orders.inspection_video_url is 'Inspection video URL from China warehouse';

alter table public.orders disable row level security;
grant select, insert, update on table public.orders to anon, authenticated;

DO $$
DECLARE
  seq_name text;
BEGIN
  SELECT pg_get_serial_sequence('public.orders', 'id') INTO seq_name;
  IF seq_name IS NOT NULL THEN
    EXECUTE format('grant usage, select on sequence %s to anon, authenticated', seq_name);
  END IF;
END $$;
