-- Migration: create products table if missing for Doukoure Import
-- Date: 2026-08-12

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price_xof bigint not null default 0,
  rating numeric,
  badge text,
  image_url text,
  category text,
  subtitle text,
  share_url text,
  estimated_weight_kg numeric,
  length_cm numeric,
  width_cm numeric,
  height_cm numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_products_rating on public.products (rating desc);
create index if not exists idx_products_category on public.products (category);

comment on table public.products is 'Product catalog for Doukoure Import frontend';
comment on column public.products.price_xof is 'Base purchase price in FCFA';
comment on column public.products.estimated_weight_kg is 'Estimated shipping weight in kilograms';
comment on column public.products.length_cm is 'Package length in centimeters';
comment on column public.products.width_cm is 'Package width in centimeters';
comment on column public.products.height_cm is 'Package height in centimeters';
