-- Migration: Sprint A foundations (state machine events, payment transactions, admin audit)
-- Date: 2026-08-12

-- ---------------------------------------------------------------------------
-- 1) Enforce explicit order status domain
-- ---------------------------------------------------------------------------
alter table public.orders
  drop constraint if exists orders_status_check;

alter table public.orders
  add constraint orders_status_check
  check (
    status in (
      'PAYMENT_PENDING',
      'PURCHASED_CHINA',
      'INSPECTION_WEIGHED_CHINA',
      'IN_TRANSIT_SN',
      'CUSTOMS_DAKAR',
      'OUT_FOR_DELIVERY',
      'DELIVERED',
      'PAID',
      'PAYMENT_FAILED'
    )
  );

-- ---------------------------------------------------------------------------
-- 2) Order transition events (state machine observability)
-- ---------------------------------------------------------------------------
create table if not exists public.order_status_events (
  id bigint generated by default as identity primary key,
  order_ref text not null,
  previous_status text,
  next_status text not null,
  source text not null default 'unknown',
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_order_status_events_order_ref
  on public.order_status_events(order_ref, created_at desc);

comment on table public.order_status_events is 'Immutable log of order lifecycle status transitions';

-- ---------------------------------------------------------------------------
-- 3) Payment transactions (idempotency and reconciliation)
-- ---------------------------------------------------------------------------
create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  order_ref text not null,
  provider text not null check (provider in ('wave', 'orange')),
  provider_reference text not null,
  amount_xof bigint not null check (amount_xof >= 0),
  status text not null check (status in ('PENDING', 'CONFIRMED', 'FAILED')),
  idempotency_key text not null,
  payer_name text,
  payer_phone text,
  metadata jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_reference),
  unique (provider, idempotency_key)
);

create index if not exists idx_payment_transactions_order_ref
  on public.payment_transactions(order_ref, created_at desc);

comment on table public.payment_transactions is 'Payment attempts and confirmations for Wave/Orange Money';

-- ---------------------------------------------------------------------------
-- 4) Admin audit trail for global rates updates
-- ---------------------------------------------------------------------------
create table if not exists public.system_settings_audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  actor text,
  before_payload jsonb,
  after_payload jsonb,
  source text,
  created_at timestamptz not null default now()
);

create index if not exists idx_system_settings_audit_logs_created_at
  on public.system_settings_audit_logs(created_at desc);

comment on table public.system_settings_audit_logs is 'Immutable audit trail for system settings changes';

-- ---------------------------------------------------------------------------
-- 5) Trigger to auto-track status transitions
-- ---------------------------------------------------------------------------
create or replace function public.log_order_status_transition()
returns trigger
language plpgsql
as $$
begin
  if new.status is distinct from old.status then
    insert into public.order_status_events (
      order_ref,
      previous_status,
      next_status,
      source,
      metadata
    )
    values (
      new.order_ref,
      old.status,
      new.status,
      'db_trigger',
      jsonb_build_object('updated_at', new.updated_at)
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_log_order_status_transition on public.orders;
create trigger trg_log_order_status_transition
after update on public.orders
for each row
execute function public.log_order_status_transition();

-- ---------------------------------------------------------------------------
-- 6) Basic RLS hardening
-- ---------------------------------------------------------------------------
alter table public.system_settings enable row level security;
alter table public.system_settings_audit_logs enable row level security;
alter table public.payment_transactions enable row level security;
alter table public.order_status_events enable row level security;

-- Read-only for public app on system settings.
drop policy if exists system_settings_select_public on public.system_settings;
create policy system_settings_select_public
on public.system_settings
for select
to anon, authenticated
using (true);

-- Writes only for service role / admin claim.
drop policy if exists system_settings_write_admin on public.system_settings;
create policy system_settings_write_admin
on public.system_settings
for all
to authenticated
using (
  coalesce((auth.jwt() -> 'app_metadata' ->> 'is_admin')::boolean, false)
  or auth.jwt() ->> 'role' = 'service_role'
)
with check (
  coalesce((auth.jwt() -> 'app_metadata' ->> 'is_admin')::boolean, false)
  or auth.jwt() ->> 'role' = 'service_role'
);

-- Payment inserts can come from client prototype and service role.
drop policy if exists payment_transactions_insert_public on public.payment_transactions;
create policy payment_transactions_insert_public
on public.payment_transactions
for insert
to anon, authenticated
with check (true);

drop policy if exists payment_transactions_select_public on public.payment_transactions;
create policy payment_transactions_select_public
on public.payment_transactions
for select
to anon, authenticated
using (true);

-- Lifecycle event insert/select for prototype observability.
drop policy if exists order_status_events_insert_public on public.order_status_events;
create policy order_status_events_insert_public
on public.order_status_events
for insert
to anon, authenticated
with check (true);

drop policy if exists order_status_events_select_public on public.order_status_events;
create policy order_status_events_select_public
on public.order_status_events
for select
to anon, authenticated
using (true);

-- Audit logs readable only to authenticated users.
drop policy if exists system_settings_audit_logs_select_authenticated on public.system_settings_audit_logs;
create policy system_settings_audit_logs_select_authenticated
on public.system_settings_audit_logs
for select
to authenticated
using (true);

-- Grants for tables / identity sequences.
grant select on public.system_settings to anon, authenticated;
grant select, insert on public.payment_transactions to anon, authenticated;
grant select, insert on public.order_status_events to anon, authenticated;
grant select, insert on public.system_settings_audit_logs to authenticated;

do $$
declare
  seq_name text;
begin
  foreach seq_name in array array[
    pg_get_serial_sequence('public.order_status_events', 'id'),
    pg_get_serial_sequence('public.payment_transactions', 'id'),
    pg_get_serial_sequence('public.system_settings_audit_logs', 'id')
  ]
  loop
    if seq_name is not null then
      execute format('grant usage, select on sequence %s to anon, authenticated', seq_name);
    end if;
  end loop;
end $$;
