-- Migration: create homepage and visual search resources
-- Date: 2026-08-12

create table if not exists public.containers (
  id bigint generated by default as identity primary key,
  container_id text,
  target_cbm numeric not null default 0,
  allocated_cbm numeric not null default 0,
  departure_date timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_containers_departure_date on public.containers (departure_date asc);

create table if not exists public.visual_search_requests (
  id bigint generated by default as identity primary key,
  file_url text not null,
  budget_xof bigint,
  size_color_qty text,
  whatsapp_phone text,
  status text not null default 'PENDING',
  created_at timestamptz not null default now()
);

create index if not exists idx_visual_search_requests_created_at
  on public.visual_search_requests (created_at desc);

-- Dev/staging friendly grants for anon key access used by frontend
alter table public.containers disable row level security;
alter table public.visual_search_requests disable row level security;

grant select on table public.containers to anon, authenticated;
grant select, insert on table public.visual_search_requests to anon, authenticated;

-- Identity sequence grants for inserts through REST
DO $$
DECLARE
  seq_name text;
BEGIN
  SELECT pg_get_serial_sequence('public.visual_search_requests', 'id') INTO seq_name;
  IF seq_name IS NOT NULL THEN
    EXECUTE format('grant usage, select on sequence %s to anon, authenticated', seq_name);
  END IF;
END $$;

-- Ensure bucket exists for visual search uploads
insert into storage.buckets (id, name, public)
values ('search-uploads', 'search-uploads', true)
on conflict (id) do nothing;

-- Storage policies for public upload/read on the specific bucket
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'search_uploads_public_read'
  ) THEN
    CREATE POLICY search_uploads_public_read
      ON storage.objects
      FOR SELECT
      TO public
      USING (bucket_id = 'search-uploads');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'search_uploads_anon_insert'
  ) THEN
    CREATE POLICY search_uploads_anon_insert
      ON storage.objects
      FOR INSERT
      TO anon, authenticated
      WITH CHECK (bucket_id = 'search-uploads');
  END IF;
END $$;

-- Seed one upcoming container if table is empty to avoid empty homepage state.
insert into public.containers (container_id, target_cbm, allocated_cbm, departure_date)
select
  'Dakar #104',
  68,
  44.2,
  now() + interval '3 days'
where not exists (select 1 from public.containers);
